name: vision_week
description: A new Flutter project. Une application mobile pour l'explorationb virtuelle d'un zoo.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true