apiVersion: v1
kind: Namespace
metadata:
  name: vision-week
  labels:
    name: vision-week
    environment: production
    app: vision-week-virtual-exploration
  annotations:
    description: "Namespace pour l'application Vision Week Virtual Exploration"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vision-week-quota
  namespace: vision-week
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vision-week-limits
  namespace: vision-week
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim

