name: vision_week_virtual_exploration
description: A new Flutter project for Vision Week Virtual Exploration.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
