name: vision_week_virtual_exploration
description: A new Flutter project for Vision Week Virtual Exploration.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.0.1
  http: ^0.13.6
  geolocator: ^12.0.0
  location: ^7.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  flutter_secure_storage: ^9.2.2
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  flutter_gen: ^5.6.0
  path: ^1.9.0
  path_provider: ^2.0.0
  flame: ^1.8.0
  flame_audio: ^2.10.2

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/generated
  integrations:
    flutter_localizations: true

assets:
  - assets/images

l10n:
  - lib/l10n/int_en.arb
  - lib/l10n/int_fr.arb
