name: vision_week_virtual_exploration
description: A new Flutter project for Vision Week Virtual Exploration.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.0.1
  http: ^1.2.1
  xml: ^6.0.1
  geolocator: ^9.0.2
  location: ^4.3.0
  provider: ^6.0.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  flutter_svg: ^1.0.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true